<?php


namespace App\Model;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Menu extends Model
{
    protected $table='menus';
    protected $fillable=[
        'uuid',
        'type',
        'title',
        'slug'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }

}
