<?php


namespace App\Model;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = [
        'uuid',
        'title',
        'desc',
        'text',
        'slug',
        'type'
    ];
    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
