<?php


namespace App\Model;


use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = [
        'uuid',
        'title',
        'desc',
        'text',
        'slug',
        'type',
        'img',
        'icon'
    ];

    public function PostMenuToAny($uuid){

        return $this->belongsToMany(Post::class,'menu_to_has',"deleted_at","row_uuid",'uuid','uuid')
            ->where('menu_to_has.menu_uuid', '=', $uuid);
    }

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
    }
}
